import type { Metadata } from "next";
import FinancesProvider from "./use-finances";
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <FinancesProvider>
        <body
          className={`${inter.className} antialiased`}
        >
          {children}
        </body>
      </FinancesProvider>
    </html>
  );
}
